using Traincrew_MultiATS_Server.Data;

namespace Traincrew_MultiATS_Server.Repositories.TtcWindowLinkRouteCondition;

public class TtcWindowLinkRouteConditionRepository(ApplicationDbContext context) : ITtcWindowLinkRouteConditionRepository
{
}
