-- Create enum type "ttc_window_type"
CREATE TYPE "ttc_window_type" AS ENUM ('home_track', 'up', 'down', 'switching');
-- Create enum type "ttc_window_link_type"
CREATE TYPE "ttc_window_link_type" AS ENUM ('up', 'down', 'switching');
-- Create "ttc_window" table
CREATE TABLE "ttc_window" ("name" character varying(100) NOT NULL, "station_id" character varying(10) NOT NULL, "type" "ttc_window_type" NOT NULL, PRIMARY KEY ("name"), CONSTRAINT "ttc_window_station_id_fkey" FOREIGN KEY ("station_id") REFERENCES "station" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "ttc_window_display_station" table
CREATE TABLE "ttc_window_display_station" ("id" bigserial NOT NULL, "ttc_window_name" character varying(100) NOT NULL, "station_id" character varying(10) NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "ttc_window_display_station_ttc_window_name_station_id_key" UNIQUE ("ttc_window_name", "station_id"), CONSTRAINT "ttc_window_display_station_station_id_fkey" FOREIGN KEY ("station_id") REFERENCES "station" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "ttc_window_display_station_ttc_window_name_fkey" FOREIGN KEY ("ttc_window_name") REFERENCES "ttc_window" ("name") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "ttc_window_link" table
CREATE TABLE "ttc_window_link" ("id" bigserial NOT NULL, "source_ttc_window_name" character varying(100) NOT NULL, "target_ttc_window_name" character varying(100) NOT NULL, "type" "ttc_window_link_type" NOT NULL, "is_empty_sending" boolean NOT NULL, "track_circuit_condition" bigint NULL, PRIMARY KEY ("id"), CONSTRAINT "ttc_window_link_source_ttc_window_name_fkey" FOREIGN KEY ("source_ttc_window_name") REFERENCES "ttc_window" ("name") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "ttc_window_link_target_ttc_window_name_fkey" FOREIGN KEY ("target_ttc_window_name") REFERENCES "ttc_window" ("name") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "ttc_window_link_track_circuit_condition_fkey" FOREIGN KEY ("track_circuit_condition") REFERENCES "track_circuit" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "ttc_window_link_route_condition" table
CREATE TABLE "ttc_window_link_route_condition" ("id" bigserial NOT NULL, "ttc_window_link_id" bigint NOT NULL, "route_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "ttc_window_link_route_condition_ttc_window_link_id_route_id_key" UNIQUE ("ttc_window_link_id", "route_id"), CONSTRAINT "ttc_window_link_route_condition_route_id_fkey" FOREIGN KEY ("route_id") REFERENCES "route" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "ttc_window_link_route_condition_ttc_window_link_id_fkey" FOREIGN KEY ("ttc_window_link_id") REFERENCES "ttc_window_link" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION);
-- Create "ttc_window_track_circuit" table
CREATE TABLE "ttc_window_track_circuit" ("id" bigserial NOT NULL, "ttc_window_name" character varying(100) NOT NULL, "track_circuit_id" bigint NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "ttc_window_track_circuit_ttc_window_name_track_circuit_id_key" UNIQUE ("ttc_window_name", "track_circuit_id"), CONSTRAINT "ttc_window_track_circuit_track_circuit_id_fkey" FOREIGN KEY ("track_circuit_id") REFERENCES "track_circuit" ("id") ON UPDATE NO ACTION ON DELETE NO ACTION, CONSTRAINT "ttc_window_track_circuit_ttc_window_name_fkey" FOREIGN KEY ("ttc_window_name") REFERENCES "ttc_window" ("name") ON UPDATE NO ACTION ON DELETE NO ACTION);
