on:
  workflow_dispatch:  {}
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v2
        - name: Extract branch name
          shell: bash
          run: echo "branch=$(echo ${GITHUB_REF#refs/heads/} | sed 's|/|_|g')" >> $GITHUB_OUTPUT
          id: extract_branch
        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3.2.0
        
        - name : Set up Docker Buildx
          uses: docker/setup-buildx-action@v3.7.1
        - name: Login to Docker harbor
          uses: docker/login-action@v3.3.0
          with:
            registry: ${{ secrets.HARBOR_ENDPOINT }}
            username: ${{ secrets.HARBOR_USERNAME }}
            password: ${{ secrets.HARBOR_PASSWORD }}
        - name: Build and push
          uses: docker/build-push-action@v6.9.0
          with:
            push: true
            platforms: linux/amd64,linux/arm64
            tags: "${{ secrets.HARBOR_ENDPOINT }}:${{ steps.extract_branch.outputs.branch }}"
            cache-from: type=gha
            cache-to: type=gha,mode=max
        