name: Unit Tests

on:
  push:
    branches:
      - feature/add_integration_test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.3.1
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build solution
        run: dotnet build --no-restore --configuration Release

      - name: Run Unit Tests
        working-directory: ./Traincrew_MultiATS_Server.UT
        run: dotnet test --no-build --configuration Release
